let CANVAS,
    CTX,
    PLAYER,
    LAST_FRAME = performance.now(),
    OBSTACLES = [],
    CAMERA_SHAKE_END = 0,
    GAME_DURATION = 0,
    MOUSE_DOWN = false,
    WAIT_FOR_RELEASE = false,
    RNG,
    DEATHS = [],
    MOUSE_POSITION = {'x': 0, 'y': 0},
    MENU = null;
